# Generated by Django 4.0.4 on 2022-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('timeout', models.FloatField(null=True)),
            ],
        ),
    ]
