name: CI

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-v4-dev-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            buildx-v4-dev-

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: WisdomPill
          password: ${{ secrets.PAT }}

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: dev=yes
          pull: true
          push: true
          tags: |
            ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}
            ghcr.io/wisdompill/smart_lock:latest-dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  test:
    runs-on: ubuntu-latest

    needs: build

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: smart_lock
          POSTGRES_PASSWORD: smart_lock
          POSTGRES_DB: smart_lock
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        credentials:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        ports:
          - 5432:5432
      redis:
        image: redis:5.0.6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        credentials:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-v4-dev-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            buildx-v4-dev-

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: WisdomPill
          password: ${{ secrets.PAT }}

      - name: Docker pull image
        id: docker_pull_image
        run: docker pull ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}

      - name: Run tests
        id: run_tests
        run: docker run --network host --env-file docker/postgres.env ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }} test

  black:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-v4-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}
          restore-keys: |
            buildx-v4-dev-

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: WisdomPill
          password: ${{ secrets.PAT }}

      - name: Docker pull image
        id: docker_pull_image
        run: docker pull ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}

      - name: Run black
        id: run_black
        run: docker run --entrypoint black ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }} --target-version py39 --check --diff .

  flake8:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-v4-dev-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            buildx-v4-dev-

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: WisdomPill
          password: ${{ secrets.PAT }}

      - name: Docker pull image
        id: docker_pull_image
        run: docker pull ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}

      - name: Run flake8
        id: run_flake8
        run: docker run --entrypoint flake8 ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}

  isort:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-v4-dev-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            buildx-v4-dev-

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: WisdomPill
          password: ${{ secrets.PAT }}

      - name: Docker pull image
        id: docker_pull_image
        run: docker pull ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }}

      - name: Run isort
        id: run_isort
        run: docker run --entrypoint isort ghcr.io/wisdompill/smart_lock:latest-dev-${{ hashFiles('smart_lock/Pipfile.lock') }} --check-only --diff .
